version: "3"
services:
  watchtower:
    image: containrrr/watchtower:1.3.0
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 90

  database_pg:
    image: postgres:13.2
    container_name: database_pg
    command: -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.max=10000 -c pg_stat_statements.track=al
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database_pg
    ports:
      - "5430:5432"
    volumes:
      - /root/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 3
    networks:
      - local_net

  cisei:
    image: index.docker.io/framaxwlad/cisei:latest
    container_name: cisei
    depends_on:
      - database_pg
    networks:
      - local_net

  grafana:
    image: grafana/grafana:7.5.4
    container_name: grafana
    restart: always
    volumes:
      - /root/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - database_pg
    networks:
      - local_net

networks:
  local_net:
    driver: bridge

volumes:
  grafana-pg-storage:
    external: true
  grafana-storage:
    external: true

