name: CI / CD

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  continuous_deployment:
    runs-on: ubuntu-latest

    if: "startsWith(github.head_ref, 'deployment/')"
    steps:
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - uses: actions/checkout@v2

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Build and deploy Docker images
        run: |
          bash cisei/build_and_push_image.sh
